### ISSUE TITLE
Duplicate declaration

### ISSUE THREAD

**Issue by mark0n** [amateo/puppet-dovecot#1] opened 2017-04-03 00:58 UTC
The following resources fail:
```
  class { 'dovecot':
    package_ensure => latest,
    enable_imap => true,
  }

  class { 'dovecot::ssl':
    options => {
      ssl           => 'required',
      ssl_cert      => '</etc/dovecot/mail.example.com-crt.pem',
      ssl_key       => '</etc/dovecot/mail.example.com-key.pem',
      ssl_protocols => '!SSLv2 !SSLv3',
    },
  }
```
The error message is:
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Class[Dovecot::Ssl] is already declared; cannot redeclare
```
Am I defining my resources in the wrong way? Note that this is rather similar to the example in the README.

**Comment by amateo** [comment] 2017-04-03 07:40
The problem is that code is prepare to pass class parameters directly from hiera instead of using the class notation, so ```dovecot::ssl``` is already included with ```ssl```.
I have to review the code in order to allow the class syntax.

**Comment by mark0n** [comment] 2017-04-04 01:34
I see. Might be worth mentioning that in the README ;-)

**Comment by amateo** [comment] 2017-04-12 11:00
I think this should be fixed with the version I have just uploaded.
With this new version you have to manually include ```dovecot::ssl``` by using the ```include_ssl``` parameter in ```dovecot``` or directly using ```class {::dovecot::ssl: .... }```

**Closed as completed by amateo** 2017-04-12 11:00 UTC

**Comment by mark0n** [comment] 2017-05-28 22:33
Works like a charm - thanks!
